// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yntzvwbilkzbzdrzawcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InludHp2d2JpbGt6Ynpkcnphd2NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgwMzUzNjEsImV4cCI6MjEwMzYxMTM2MX0.kKRYDBqnu3sZCrj-IZ3C4qRTSd8TSdj4GnwzzZ39qBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});